"""The Country entity: name + ISO code, all in one place.

Every other enrichment module (registration.py, callsign.py,
aircraft_database.py) stores only an ISO code and resolves the display name
through country_by_iso() — so "Czech Republic" is spelled exactly once,
here. Flag rendering is a frontend presentation concern (static/index.html's
flagHtml(), via the flag-icons SVG library) — this module only ever hands
out the ISO code, never a rendered flag.

Covers essentially every ICAO member state (needed so registration.py's
nationality-mark table has somewhere to resolve to — a prefix mapping to an
ISO code not listed here would silently resolve to nothing) plus a handful
of ICAO-registered dependencies/territories with their own registration
prefix (Hong Kong, Macau). Not a claim of 100% completeness for very small
territories with no active civil aircraft register.
"""

COUNTRIES = [
    {"name": "Afghanistan", "iso": "AF"},
    {"name": "Albania", "iso": "AL"},
    {"name": "Algeria", "iso": "DZ"},
    {"name": "Andorra", "iso": "AD"},
    {"name": "Angola", "iso": "AO"},
    {"name": "Antigua and Barbuda", "iso": "AG"},
    {"name": "Argentina", "iso": "AR"},
    {"name": "Armenia", "iso": "AM"},
    {"name": "Aruba", "iso": "AW"},
    {"name": "Australia", "iso": "AU"},
    {"name": "Austria", "iso": "AT"},
    {"name": "Azerbaijan", "iso": "AZ"},
    {"name": "Bahamas", "iso": "BS"},
    {"name": "Bahrain", "iso": "BH"},
    {"name": "Bangladesh", "iso": "BD"},
    {"name": "Barbados", "iso": "BB"},
    {"name": "Belarus", "iso": "BY"},
    {"name": "Belgium", "iso": "BE"},
    {"name": "Belize", "iso": "BZ"},
    {"name": "Benin", "iso": "BJ"},
    {"name": "Bhutan", "iso": "BT"},
    {"name": "Bolivia", "iso": "BO"},
    {"name": "Bosnia and Herzegovina", "iso": "BA"},
    {"name": "Botswana", "iso": "BW"},
    {"name": "Brazil", "iso": "BR"},
    {"name": "Brunei", "iso": "BN"},
    {"name": "Bulgaria", "iso": "BG"},
    {"name": "Burkina Faso", "iso": "BF"},
    {"name": "Burundi", "iso": "BI"},
    {"name": "Cambodia", "iso": "KH"},
    {"name": "Cameroon", "iso": "CM"},
    {"name": "Canada", "iso": "CA"},
    {"name": "Cape Verde", "iso": "CV"},
    {"name": "Central African Republic", "iso": "CF"},
    {"name": "Chad", "iso": "TD"},
    {"name": "Chile", "iso": "CL"},
    {"name": "China", "iso": "CN"},
    {"name": "Colombia", "iso": "CO"},
    {"name": "Comoros", "iso": "KM"},
    {"name": "Congo (Republic)", "iso": "CG"},
    {"name": "Costa Rica", "iso": "CR"},
    {"name": "Croatia", "iso": "HR"},
    {"name": "Côte d'Ivoire", "iso": "CI"},
    {"name": "Cuba", "iso": "CU"},
    {"name": "Cyprus", "iso": "CY"},
    {"name": "Czech Republic", "iso": "CZ"},
    {"name": "Democratic Republic of the Congo", "iso": "CD"},
    {"name": "Denmark", "iso": "DK"},
    {"name": "Djibouti", "iso": "DJ"},
    {"name": "Dominica", "iso": "DM"},
    {"name": "Dominican Republic", "iso": "DO"},
    {"name": "Ecuador", "iso": "EC"},
    {"name": "Egypt", "iso": "EG"},
    {"name": "El Salvador", "iso": "SV"},
    {"name": "Equatorial Guinea", "iso": "GQ"},
    {"name": "Eritrea", "iso": "ER"},
    {"name": "Estonia", "iso": "EE"},
    {"name": "Eswatini", "iso": "SZ"},
    {"name": "Ethiopia", "iso": "ET"},
    {"name": "Fiji", "iso": "FJ"},
    {"name": "Finland", "iso": "FI"},
    {"name": "France", "iso": "FR"},
    {"name": "Gabon", "iso": "GA"},
    {"name": "Gambia", "iso": "GM"},
    {"name": "Georgia", "iso": "GE"},
    {"name": "Germany", "iso": "DE"},
    {"name": "Ghana", "iso": "GH"},
    {"name": "Greece", "iso": "GR"},
    {"name": "Grenada", "iso": "GD"},
    {"name": "Guatemala", "iso": "GT"},
    {"name": "Guinea", "iso": "GN"},
    {"name": "Guinea-Bissau", "iso": "GW"},
    {"name": "Guyana", "iso": "GY"},
    {"name": "Haiti", "iso": "HT"},
    {"name": "Honduras", "iso": "HN"},
    {"name": "Hong Kong", "iso": "HK"},
    {"name": "Hungary", "iso": "HU"},
    {"name": "Iceland", "iso": "IS"},
    {"name": "India", "iso": "IN"},
    {"name": "Indonesia", "iso": "ID"},
    {"name": "Iran", "iso": "IR"},
    {"name": "Iraq", "iso": "IQ"},
    {"name": "Ireland", "iso": "IE"},
    {"name": "Israel", "iso": "IL"},
    {"name": "Italy", "iso": "IT"},
    {"name": "Jamaica", "iso": "JM"},
    {"name": "Japan", "iso": "JP"},
    {"name": "Jordan", "iso": "JO"},
    {"name": "Kazakhstan", "iso": "KZ"},
    {"name": "Kenya", "iso": "KE"},
    {"name": "Kiribati", "iso": "KI"},
    {"name": "Kuwait", "iso": "KW"},
    {"name": "Kyrgyzstan", "iso": "KG"},
    {"name": "Laos", "iso": "LA"},
    {"name": "Latvia", "iso": "LV"},
    {"name": "Lebanon", "iso": "LB"},
    {"name": "Lesotho", "iso": "LS"},
    {"name": "Liberia", "iso": "LR"},
    {"name": "Libya", "iso": "LY"},
    {"name": "Liechtenstein", "iso": "LI"},
    {"name": "Lithuania", "iso": "LT"},
    {"name": "Luxembourg", "iso": "LU"},
    {"name": "Macau", "iso": "MO"},
    {"name": "Madagascar", "iso": "MG"},
    {"name": "Malawi", "iso": "MW"},
    {"name": "Malaysia", "iso": "MY"},
    {"name": "Maldives", "iso": "MV"},
    {"name": "Mali", "iso": "ML"},
    {"name": "Malta", "iso": "MT"},
    {"name": "Marshall Islands", "iso": "MH"},
    {"name": "Mauritania", "iso": "MR"},
    {"name": "Mauritius", "iso": "MU"},
    {"name": "Mexico", "iso": "MX"},
    {"name": "Micronesia", "iso": "FM"},
    {"name": "Moldova", "iso": "MD"},
    {"name": "Monaco", "iso": "MC"},
    {"name": "Mongolia", "iso": "MN"},
    {"name": "Montenegro", "iso": "ME"},
    {"name": "Morocco", "iso": "MA"},
    {"name": "Mozambique", "iso": "MZ"},
    {"name": "Myanmar", "iso": "MM"},
    {"name": "Namibia", "iso": "NA"},
    {"name": "Nauru", "iso": "NR"},
    {"name": "Nepal", "iso": "NP"},
    {"name": "Netherlands", "iso": "NL"},
    {"name": "New Zealand", "iso": "NZ"},
    {"name": "Nicaragua", "iso": "NI"},
    {"name": "Niger", "iso": "NE"},
    {"name": "Nigeria", "iso": "NG"},
    {"name": "North Korea", "iso": "KP"},
    {"name": "North Macedonia", "iso": "MK"},
    {"name": "Norway", "iso": "NO"},
    {"name": "Oman", "iso": "OM"},
    {"name": "Pakistan", "iso": "PK"},
    {"name": "Palau", "iso": "PW"},
    {"name": "Panama", "iso": "PA"},
    {"name": "Papua New Guinea", "iso": "PG"},
    {"name": "Paraguay", "iso": "PY"},
    {"name": "Peru", "iso": "PE"},
    {"name": "Philippines", "iso": "PH"},
    {"name": "Poland", "iso": "PL"},
    {"name": "Portugal", "iso": "PT"},
    {"name": "Qatar", "iso": "QA"},
    {"name": "Romania", "iso": "RO"},
    {"name": "Russia", "iso": "RU"},
    {"name": "Rwanda", "iso": "RW"},
    {"name": "Saint Kitts and Nevis", "iso": "KN"},
    {"name": "Saint Lucia", "iso": "LC"},
    {"name": "Saint Vincent and the Grenadines", "iso": "VC"},
    {"name": "Samoa", "iso": "WS"},
    {"name": "San Marino", "iso": "SM"},
    {"name": "Sao Tome and Principe", "iso": "ST"},
    {"name": "Saudi Arabia", "iso": "SA"},
    {"name": "Senegal", "iso": "SN"},
    {"name": "Serbia", "iso": "RS"},
    {"name": "Seychelles", "iso": "SC"},
    {"name": "Sierra Leone", "iso": "SL"},
    {"name": "Singapore", "iso": "SG"},
    {"name": "Slovakia", "iso": "SK"},
    {"name": "Slovenia", "iso": "SI"},
    {"name": "Solomon Islands", "iso": "SB"},
    {"name": "Somalia", "iso": "SO"},
    {"name": "South Africa", "iso": "ZA"},
    {"name": "South Korea", "iso": "KR"},
    {"name": "South Sudan", "iso": "SS"},
    {"name": "Spain", "iso": "ES"},
    {"name": "Sri Lanka", "iso": "LK"},
    {"name": "Sudan", "iso": "SD"},
    {"name": "Suriname", "iso": "SR"},
    {"name": "Sweden", "iso": "SE"},
    {"name": "Switzerland", "iso": "CH"},
    {"name": "Syria", "iso": "SY"},
    {"name": "Taiwan", "iso": "TW"},
    {"name": "Tajikistan", "iso": "TJ"},
    {"name": "Tanzania", "iso": "TZ"},
    {"name": "Thailand", "iso": "TH"},
    {"name": "Togo", "iso": "TG"},
    {"name": "Tonga", "iso": "TO"},
    {"name": "Trinidad and Tobago", "iso": "TT"},
    {"name": "Tunisia", "iso": "TN"},
    {"name": "Turkey", "iso": "TR"},
    {"name": "Turkmenistan", "iso": "TM"},
    {"name": "Tuvalu", "iso": "TV"},
    {"name": "Uganda", "iso": "UG"},
    {"name": "Ukraine", "iso": "UA"},
    {"name": "United Arab Emirates", "iso": "AE"},
    {"name": "United Kingdom", "iso": "GB"},
    {"name": "United States", "iso": "US"},
    {"name": "Uruguay", "iso": "UY"},
    {"name": "Uzbekistan", "iso": "UZ"},
    {"name": "Vanuatu", "iso": "VU"},
    {"name": "Venezuela", "iso": "VE"},
    {"name": "Vietnam", "iso": "VN"},
    {"name": "Yemen", "iso": "YE"},
    {"name": "Zambia", "iso": "ZM"},
    {"name": "Zimbabwe", "iso": "ZW"},
]
COUNTRIES_BY_ISO = {c["iso"]: c for c in COUNTRIES}
COUNTRIES_BY_NAME = {c["name"].lower(): c["iso"] for c in COUNTRIES}

# Aliases for official/long-form country names live sources report under a
# different string than this table's canonical short name — found via a
# real aircraft (PH-BHG / KLM564), whose OpenSky origin_country is "Kingdom
# of the Netherlands", not "Netherlands", so country_iso_for_name() silently
# returned None and the sidebar showed the country with no flag. Checked as
# a fallback only, same "extend on the next real gap" spirit as
# registration.py's own prefix table.
#
# Generated from the ISO 3166-1 dataset (pycountry/iso-codes,
# src/pycountry/databases/iso3166-1.json — the "official_name"/"common_name"/
# "name" fields, wherever they differ from this table's own canonical name)
# rather than hand-guessed, after the Netherlands case above showed a
# hand-guessed table can't be trusted to get word order right (an earlier
# version of this file had "iran (islamic republic of)", "bolivia
# (plurinational state of)", "venezuela (bolivarian republic of)" and "the
# bahamas" — none of which are the real ISO string). "swaziland" (Eswatini's
# pre-2018 name), "burma" (Myanmar's pre-1989 name), "the former
# yugoslav republic of macedonia" (North Macedonia's pre-2019 UN/ISO name)
# and "republic of korea" (South Korea's actual official name — the ISO
# dataset's own "name" field for KR is oddly reordered as "Korea, Republic
# of" with no natural-order "official_name" at all) are kept from the
# hand-written version since the current ISO dataset doesn't (re)produce
# them — still real, just not derivable from that JSON file alone. Not
# exhaustive.
COUNTRY_NAME_ALIASES = {
    "arab republic of egypt": "EG",
    "argentine republic": "AR",
    "bolivarian republic of venezuela": "VE",
    "bolivia, plurinational state of": "BO",
    "brunei darussalam": "BN",
    "burma": "MM",
    "cabo verde": "CV",
    "commonwealth of dominica": "DM",
    "commonwealth of the bahamas": "BS",
    "congo": "CG",
    "congo, the democratic republic of the": "CD",
    "czechia": "CZ",
    "democratic people's republic of korea": "KP",
    "democratic republic of sao tome and principe": "ST",
    "democratic socialist republic of sri lanka": "LK",
    "eastern republic of uruguay": "UY",
    "federal democratic republic of ethiopia": "ET",
    "federal democratic republic of nepal": "NP",
    "federal republic of germany": "DE",
    "federal republic of nigeria": "NG",
    "federal republic of somalia": "SO",
    "federated states of micronesia": "FM",
    "federative republic of brazil": "BR",
    "french republic": "FR",
    "gabonese republic": "GA",
    "grand duchy of luxembourg": "LU",
    "hashemite kingdom of jordan": "JO",
    "hellenic republic": "GR",
    "hong kong special administrative region of china": "HK",
    "independent state of papua new guinea": "PG",
    "independent state of samoa": "WS",
    "iran, islamic republic of": "IR",
    "islamic republic of afghanistan": "AF",
    "islamic republic of iran": "IR",
    "islamic republic of mauritania": "MR",
    "islamic republic of pakistan": "PK",
    "italian republic": "IT",
    "kingdom of bahrain": "BH",
    "kingdom of belgium": "BE",
    "kingdom of bhutan": "BT",
    "kingdom of cambodia": "KH",
    "kingdom of denmark": "DK",
    "kingdom of eswatini": "SZ",
    "kingdom of lesotho": "LS",
    "kingdom of morocco": "MA",
    "kingdom of norway": "NO",
    "kingdom of saudi arabia": "SA",
    "kingdom of spain": "ES",
    "kingdom of sweden": "SE",
    "kingdom of thailand": "TH",
    "kingdom of the netherlands": "NL",
    "kingdom of tonga": "TO",
    "korea, democratic people's republic of": "KP",
    "korea, republic of": "KR",
    "republic of korea": "KR",
    "kyrgyz republic": "KG",
    "lao people's democratic republic": "LA",
    "lebanese republic": "LB",
    "macao": "MO",
    "macao special administrative region of china": "MO",
    "micronesia, federated states of": "FM",
    "moldova, republic of": "MD",
    "people's democratic republic of algeria": "DZ",
    "people's republic of bangladesh": "BD",
    "people's republic of china": "CN",
    "plurinational state of bolivia": "BO",
    "portuguese republic": "PT",
    "principality of andorra": "AD",
    "principality of liechtenstein": "LI",
    "principality of monaco": "MC",
    "republic of albania": "AL",
    "republic of angola": "AO",
    "republic of armenia": "AM",
    "republic of austria": "AT",
    "republic of azerbaijan": "AZ",
    "republic of belarus": "BY",
    "republic of benin": "BJ",
    "republic of bosnia and herzegovina": "BA",
    "republic of botswana": "BW",
    "republic of bulgaria": "BG",
    "republic of burundi": "BI",
    "republic of cabo verde": "CV",
    "republic of cameroon": "CM",
    "republic of chad": "TD",
    "republic of chile": "CL",
    "republic of colombia": "CO",
    "republic of costa rica": "CR",
    "republic of croatia": "HR",
    "republic of cuba": "CU",
    "republic of cyprus": "CY",
    "republic of côte d'ivoire": "CI",
    "republic of djibouti": "DJ",
    "republic of ecuador": "EC",
    "republic of el salvador": "SV",
    "republic of equatorial guinea": "GQ",
    "republic of estonia": "EE",
    "republic of fiji": "FJ",
    "republic of finland": "FI",
    "republic of ghana": "GH",
    "republic of guatemala": "GT",
    "republic of guinea": "GN",
    "republic of guinea-bissau": "GW",
    "republic of guyana": "GY",
    "republic of haiti": "HT",
    "republic of honduras": "HN",
    "republic of iceland": "IS",
    "republic of india": "IN",
    "republic of indonesia": "ID",
    "republic of iraq": "IQ",
    "republic of kazakhstan": "KZ",
    "republic of kenya": "KE",
    "republic of kiribati": "KI",
    "republic of latvia": "LV",
    "republic of liberia": "LR",
    "republic of lithuania": "LT",
    "republic of madagascar": "MG",
    "republic of malawi": "MW",
    "republic of maldives": "MV",
    "republic of mali": "ML",
    "republic of malta": "MT",
    "republic of mauritius": "MU",
    "republic of moldova": "MD",
    "republic of mozambique": "MZ",
    "republic of myanmar": "MM",
    "republic of namibia": "NA",
    "republic of nauru": "NR",
    "republic of nicaragua": "NI",
    "republic of north macedonia": "MK",
    "republic of palau": "PW",
    "republic of panama": "PA",
    "republic of paraguay": "PY",
    "republic of peru": "PE",
    "republic of poland": "PL",
    "republic of san marino": "SM",
    "republic of senegal": "SN",
    "republic of serbia": "RS",
    "republic of seychelles": "SC",
    "republic of sierra leone": "SL",
    "republic of singapore": "SG",
    "republic of slovenia": "SI",
    "republic of south africa": "ZA",
    "republic of south sudan": "SS",
    "republic of suriname": "SR",
    "republic of tajikistan": "TJ",
    "republic of the congo": "CG",
    "republic of the gambia": "GM",
    "republic of the marshall islands": "MH",
    "republic of the niger": "NE",
    "republic of the philippines": "PH",
    "republic of the sudan": "SD",
    "republic of trinidad and tobago": "TT",
    "republic of tunisia": "TN",
    "republic of türkiye": "TR",
    "republic of uganda": "UG",
    "republic of uzbekistan": "UZ",
    "republic of vanuatu": "VU",
    "republic of yemen": "YE",
    "republic of zambia": "ZM",
    "republic of zimbabwe": "ZW",
    "russian federation": "RU",
    "rwandese republic": "RW",
    "slovak republic": "SK",
    "socialist republic of viet nam": "VN",
    "state of eritrea": "ER",
    "state of israel": "IL",
    "state of kuwait": "KW",
    "state of qatar": "QA",
    "sultanate of oman": "OM",
    "swaziland": "SZ",
    "swiss confederation": "CH",
    "syrian arab republic": "SY",
    "tanzania, united republic of": "TZ",
    "the former yugoslav republic of macedonia": "MK",
    "togolese republic": "TG",
    "türkiye": "TR",
    "union of the comoros": "KM",
    "united kingdom of great britain and northern ireland": "GB",
    "united mexican states": "MX",
    "united republic of tanzania": "TZ",
    "united states of america": "US",
    "venezuela, bolivarian republic of": "VE",
    "viet nam": "VN",
}


def country_by_iso(iso_code):
    """Returns {"name", "iso"} for a 2-letter ISO code, or None."""
    if not iso_code:
        return None
    return COUNTRIES_BY_ISO.get(iso_code.upper())


def country_iso_for_name(name):
    """Reverse lookup: country name -> ISO code, or None.

    Lets a live-sourced country string (e.g. OpenSky's own origin_country)
    still get a flag when its exact name happens to match this table — the
    flag is then a presentation add-on for a value whose source/confidence
    stay exactly as they were, not an enrichment result in its own right.
    Exact case-insensitive match only; no fuzzy matching, since a wrong
    match would show the wrong flag rather than just no flag.
    """
    if not name:
        return None
    key = name.strip().lower()
    return COUNTRIES_BY_NAME.get(key) or COUNTRY_NAME_ALIASES.get(key)


# Region mapping for the zone-search quick-open preset feature.
# Maps ISO 2-letter country codes to one of 6 curated regions.
# Built from standard continent classification collapsed into these buckets,
# with explicit overrides for "industry convention" cases (e.g., Turkey is
# grouped under Europe since its curated airports — IST, SAW — are listed there).
REGION_BY_COUNTRY_ISO = {
    # North America
    "US": "North America", "CA": "North America", "MX": "North America",
    "BZ": "North America", "CR": "North America", "SV": "North America",
    "GT": "North America", "HN": "North America", "NI": "North America",
    "PA": "North America",
    # Europe
    "AT": "Europe", "BE": "Europe", "BG": "Europe", "HR": "Europe",
    "CY": "Europe", "CZ": "Europe", "DK": "Europe", "EE": "Europe",
    "FI": "Europe", "FR": "Europe", "DE": "Europe", "GR": "Europe",
    "HU": "Europe", "IE": "Europe", "IT": "Europe", "LV": "Europe",
    "LT": "Europe", "LU": "Europe", "MT": "Europe", "NL": "Europe",
    "PL": "Europe", "PT": "Europe", "RO": "Europe", "SK": "Europe",
    "SI": "Europe", "ES": "Europe", "SE": "Europe", "CH": "Europe",
    "GB": "Europe", "NO": "Europe", "IS": "Europe", "AD": "Europe",
    "BY": "Europe", "RS": "Europe", "UA": "Europe", "MD": "Europe",
    "TR": "Europe", "AZ": "Europe", "GE": "Europe", "AM": "Europe",
    "AL": "Europe", "BA": "Europe", "MK": "Europe", "XK": "Europe",
    "RU": "Europe",
    # Asia & Middle East
    "AE": "Asia & Middle East", "SA": "Asia & Middle East", "QA": "Asia & Middle East",
    "OM": "Asia & Middle East", "YE": "Asia & Middle East", "JO": "Asia & Middle East",
    "LB": "Asia & Middle East", "SY": "Asia & Middle East", "IQ": "Asia & Middle East",
    "IR": "Asia & Middle East", "KW": "Asia & Middle East", "BH": "Asia & Middle East",
    "IL": "Asia & Middle East", "PS": "Asia & Middle East", "KZ": "Asia & Middle East",
    "UZ": "Asia & Middle East", "TM": "Asia & Middle East", "KG": "Asia & Middle East",
    "AF": "Asia & Middle East", "PK": "Asia & Middle East", "IN": "Asia & Middle East",
    "BD": "Asia & Middle East", "BT": "Asia & Middle East", "NP": "Asia & Middle East",
    "LK": "Asia & Middle East", "MM": "Asia & Middle East", "TH": "Asia & Middle East",
    "LA": "Asia & Middle East", "KH": "Asia & Middle East", "VN": "Asia & Middle East",
    "MY": "Asia & Middle East", "SG": "Asia & Middle East", "BN": "Asia & Middle East",
    "ID": "Asia & Middle East", "PH": "Asia & Middle East", "TL": "Asia & Middle East",
    "CN": "Asia & Middle East", "MN": "Asia & Middle East", "KP": "Asia & Middle East",
    "KR": "Asia & Middle East", "JP": "Asia & Middle East", "TW": "Asia & Middle East",
    "HK": "Asia & Middle East", "MO": "Asia & Middle East", "TH": "Asia & Middle East",
    # Latin America & Caribbean
    "AG": "Latin America & Caribbean", "BS": "Latin America & Caribbean",
    "BB": "Latin America & Caribbean", "BM": "Latin America & Caribbean",
    "CU": "Latin America & Caribbean", "DO": "Latin America & Caribbean",
    "DM": "Latin America & Caribbean", "GD": "Latin America & Caribbean",
    "HT": "Latin America & Caribbean", "JM": "Latin America & Caribbean",
    "KN": "Latin America & Caribbean", "LC": "Latin America & Caribbean",
    "VC": "Latin America & Caribbean", "TT": "Latin America & Caribbean",
    "AR": "Latin America & Caribbean", "BO": "Latin America & Caribbean",
    "BR": "Latin America & Caribbean", "CL": "Latin America & Caribbean",
    "CO": "Latin America & Caribbean", "EC": "Latin America & Caribbean",
    "GY": "Latin America & Caribbean", "PY": "Latin America & Caribbean",
    "PE": "Latin America & Caribbean", "SR": "Latin America & Caribbean",
    "UY": "Latin America & Caribbean", "VE": "Latin America & Caribbean",
    # Africa
    "DZ": "Africa", "AO": "Africa", "BJ": "Africa", "BW": "Africa",
    "BF": "Africa", "BI": "Africa", "CM": "Africa", "CV": "Africa",
    "CF": "Africa", "TD": "Africa", "KM": "Africa", "CG": "Africa",
    "CD": "Africa", "DJ": "Africa", "EG": "Africa", "GQ": "Africa",
    "ER": "Africa", "ET": "Africa", "GA": "Africa", "GM": "Africa",
    "GH": "Africa", "GN": "Africa", "GW": "Africa", "CI": "Africa",
    "KE": "Africa", "LS": "Africa", "LR": "Africa", "LY": "Africa",
    "MG": "Africa", "MW": "Africa", "ML": "Africa", "MR": "Africa",
    "MU": "Africa", "MA": "Africa", "MZ": "Africa", "NA": "Africa",
    "NE": "Africa", "NG": "Africa", "RW": "Africa", "ST": "Africa",
    "SN": "Africa", "SC": "Africa", "SL": "Africa", "SO": "Africa",
    "ZA": "Africa", "SS": "Africa", "SD": "Africa", "SZ": "Africa",
    "TZ": "Africa", "TG": "Africa", "TN": "Africa", "UG": "Africa",
    "ZM": "Africa", "ZW": "Africa",
    # Australia & Oceania
    "AU": "Australia & Oceania", "NZ": "Australia & Oceania",
    "FJ": "Australia & Oceania", "KI": "Australia & Oceania",
    "MH": "Australia & Oceania", "FM": "Australia & Oceania",
    "NR": "Australia & Oceania", "PW": "Australia & Oceania",
    "PG": "Australia & Oceania", "WS": "Australia & Oceania",
    "SB": "Australia & Oceania", "TO": "Australia & Oceania",
    "TV": "Australia & Oceania", "VU": "Australia & Oceania",
}


def region_for_country_iso(iso_code):
    """Returns the region name for a 2-letter ISO code, or None.

    Maps a country to one of six curated regions used by the zone-search
    quick-open preset feature: North America, Europe, Asia & Middle East,
    Latin America & Caribbean, Africa, Australia & Oceania.
    """
    if not iso_code:
        return None
    return REGION_BY_COUNTRY_ISO.get(iso_code.upper())
