"""The Country entity: name + ISO code, all in one place.

Every other enrichment module (registration.py, callsign.py,
aircraft_database.py) stores only an ISO code and resolves the display name
through country_by_iso() — so "Czech Republic" is spelled exactly once,
here. Flag rendering is a frontend presentation concern (static/index.html's
flagHtml(), via the flag-icons SVG library) — this module only ever hands
out the ISO code, never a rendered flag.

Covers essentially every ICAO member state (needed so registration.py's
nationality-mark table has somewhere to resolve to — a prefix mapping to an
ISO code not listed here would silently resolve to nothing) plus a handful
of ICAO-registered dependencies/territories with their own registration
prefix (Hong Kong, Macau). Not a claim of 100% completeness for very small
territories with no active civil aircraft register.
"""

COUNTRIES = [
    {"name": "Afghanistan", "iso": "AF"},
    {"name": "Albania", "iso": "AL"},
    {"name": "Algeria", "iso": "DZ"},
    {"name": "Andorra", "iso": "AD"},
    {"name": "Angola", "iso": "AO"},
    {"name": "Antigua and Barbuda", "iso": "AG"},
    {"name": "Argentina", "iso": "AR"},
    {"name": "Armenia", "iso": "AM"},
    {"name": "Aruba", "iso": "AW"},
    {"name": "Australia", "iso": "AU"},
    {"name": "Austria", "iso": "AT"},
    {"name": "Azerbaijan", "iso": "AZ"},
    {"name": "Bahamas", "iso": "BS"},
    {"name": "Bahrain", "iso": "BH"},
    {"name": "Bangladesh", "iso": "BD"},
    {"name": "Barbados", "iso": "BB"},
    {"name": "Belarus", "iso": "BY"},
    {"name": "Belgium", "iso": "BE"},
    {"name": "Belize", "iso": "BZ"},
    {"name": "Benin", "iso": "BJ"},
    {"name": "Bhutan", "iso": "BT"},
    {"name": "Bolivia", "iso": "BO"},
    {"name": "Bosnia and Herzegovina", "iso": "BA"},
    {"name": "Botswana", "iso": "BW"},
    {"name": "Brazil", "iso": "BR"},
    {"name": "Brunei", "iso": "BN"},
    {"name": "Bulgaria", "iso": "BG"},
    {"name": "Burkina Faso", "iso": "BF"},
    {"name": "Burundi", "iso": "BI"},
    {"name": "Cambodia", "iso": "KH"},
    {"name": "Cameroon", "iso": "CM"},
    {"name": "Canada", "iso": "CA"},
    {"name": "Cape Verde", "iso": "CV"},
    {"name": "Central African Republic", "iso": "CF"},
    {"name": "Chad", "iso": "TD"},
    {"name": "Chile", "iso": "CL"},
    {"name": "China", "iso": "CN"},
    {"name": "Colombia", "iso": "CO"},
    {"name": "Comoros", "iso": "KM"},
    {"name": "Congo (Republic)", "iso": "CG"},
    {"name": "Costa Rica", "iso": "CR"},
    {"name": "Croatia", "iso": "HR"},
    {"name": "Côte d'Ivoire", "iso": "CI"},
    {"name": "Cuba", "iso": "CU"},
    {"name": "Cyprus", "iso": "CY"},
    {"name": "Czech Republic", "iso": "CZ"},
    {"name": "Democratic Republic of the Congo", "iso": "CD"},
    {"name": "Denmark", "iso": "DK"},
    {"name": "Djibouti", "iso": "DJ"},
    {"name": "Dominica", "iso": "DM"},
    {"name": "Dominican Republic", "iso": "DO"},
    {"name": "Ecuador", "iso": "EC"},
    {"name": "Egypt", "iso": "EG"},
    {"name": "El Salvador", "iso": "SV"},
    {"name": "Equatorial Guinea", "iso": "GQ"},
    {"name": "Eritrea", "iso": "ER"},
    {"name": "Estonia", "iso": "EE"},
    {"name": "Eswatini", "iso": "SZ"},
    {"name": "Ethiopia", "iso": "ET"},
    {"name": "Fiji", "iso": "FJ"},
    {"name": "Finland", "iso": "FI"},
    {"name": "France", "iso": "FR"},
    {"name": "Gabon", "iso": "GA"},
    {"name": "Gambia", "iso": "GM"},
    {"name": "Georgia", "iso": "GE"},
    {"name": "Germany", "iso": "DE"},
    {"name": "Ghana", "iso": "GH"},
    {"name": "Greece", "iso": "GR"},
    {"name": "Grenada", "iso": "GD"},
    {"name": "Guatemala", "iso": "GT"},
    {"name": "Guinea", "iso": "GN"},
    {"name": "Guinea-Bissau", "iso": "GW"},
    {"name": "Guyana", "iso": "GY"},
    {"name": "Haiti", "iso": "HT"},
    {"name": "Honduras", "iso": "HN"},
    {"name": "Hong Kong", "iso": "HK"},
    {"name": "Hungary", "iso": "HU"},
    {"name": "Iceland", "iso": "IS"},
    {"name": "India", "iso": "IN"},
    {"name": "Indonesia", "iso": "ID"},
    {"name": "Iran", "iso": "IR"},
    {"name": "Iraq", "iso": "IQ"},
    {"name": "Ireland", "iso": "IE"},
    {"name": "Israel", "iso": "IL"},
    {"name": "Italy", "iso": "IT"},
    {"name": "Jamaica", "iso": "JM"},
    {"name": "Japan", "iso": "JP"},
    {"name": "Jordan", "iso": "JO"},
    {"name": "Kazakhstan", "iso": "KZ"},
    {"name": "Kenya", "iso": "KE"},
    {"name": "Kiribati", "iso": "KI"},
    {"name": "Kuwait", "iso": "KW"},
    {"name": "Kyrgyzstan", "iso": "KG"},
    {"name": "Laos", "iso": "LA"},
    {"name": "Latvia", "iso": "LV"},
    {"name": "Lebanon", "iso": "LB"},
    {"name": "Lesotho", "iso": "LS"},
    {"name": "Liberia", "iso": "LR"},
    {"name": "Libya", "iso": "LY"},
    {"name": "Liechtenstein", "iso": "LI"},
    {"name": "Lithuania", "iso": "LT"},
    {"name": "Luxembourg", "iso": "LU"},
    {"name": "Macau", "iso": "MO"},
    {"name": "Madagascar", "iso": "MG"},
    {"name": "Malawi", "iso": "MW"},
    {"name": "Malaysia", "iso": "MY"},
    {"name": "Maldives", "iso": "MV"},
    {"name": "Mali", "iso": "ML"},
    {"name": "Malta", "iso": "MT"},
    {"name": "Marshall Islands", "iso": "MH"},
    {"name": "Mauritania", "iso": "MR"},
    {"name": "Mauritius", "iso": "MU"},
    {"name": "Mexico", "iso": "MX"},
    {"name": "Micronesia", "iso": "FM"},
    {"name": "Moldova", "iso": "MD"},
    {"name": "Monaco", "iso": "MC"},
    {"name": "Mongolia", "iso": "MN"},
    {"name": "Montenegro", "iso": "ME"},
    {"name": "Morocco", "iso": "MA"},
    {"name": "Mozambique", "iso": "MZ"},
    {"name": "Myanmar", "iso": "MM"},
    {"name": "Namibia", "iso": "NA"},
    {"name": "Nauru", "iso": "NR"},
    {"name": "Nepal", "iso": "NP"},
    {"name": "Netherlands", "iso": "NL"},
    {"name": "New Zealand", "iso": "NZ"},
    {"name": "Nicaragua", "iso": "NI"},
    {"name": "Niger", "iso": "NE"},
    {"name": "Nigeria", "iso": "NG"},
    {"name": "North Korea", "iso": "KP"},
    {"name": "North Macedonia", "iso": "MK"},
    {"name": "Norway", "iso": "NO"},
    {"name": "Oman", "iso": "OM"},
    {"name": "Pakistan", "iso": "PK"},
    {"name": "Palau", "iso": "PW"},
    {"name": "Panama", "iso": "PA"},
    {"name": "Papua New Guinea", "iso": "PG"},
    {"name": "Paraguay", "iso": "PY"},
    {"name": "Peru", "iso": "PE"},
    {"name": "Philippines", "iso": "PH"},
    {"name": "Poland", "iso": "PL"},
    {"name": "Portugal", "iso": "PT"},
    {"name": "Qatar", "iso": "QA"},
    {"name": "Romania", "iso": "RO"},
    {"name": "Russia", "iso": "RU"},
    {"name": "Rwanda", "iso": "RW"},
    {"name": "Saint Kitts and Nevis", "iso": "KN"},
    {"name": "Saint Lucia", "iso": "LC"},
    {"name": "Saint Vincent and the Grenadines", "iso": "VC"},
    {"name": "Samoa", "iso": "WS"},
    {"name": "San Marino", "iso": "SM"},
    {"name": "Sao Tome and Principe", "iso": "ST"},
    {"name": "Saudi Arabia", "iso": "SA"},
    {"name": "Senegal", "iso": "SN"},
    {"name": "Serbia", "iso": "RS"},
    {"name": "Seychelles", "iso": "SC"},
    {"name": "Sierra Leone", "iso": "SL"},
    {"name": "Singapore", "iso": "SG"},
    {"name": "Slovakia", "iso": "SK"},
    {"name": "Slovenia", "iso": "SI"},
    {"name": "Solomon Islands", "iso": "SB"},
    {"name": "Somalia", "iso": "SO"},
    {"name": "South Africa", "iso": "ZA"},
    {"name": "South Korea", "iso": "KR"},
    {"name": "Spain", "iso": "ES"},
    {"name": "Sri Lanka", "iso": "LK"},
    {"name": "Sudan", "iso": "SD"},
    {"name": "Suriname", "iso": "SR"},
    {"name": "Sweden", "iso": "SE"},
    {"name": "Switzerland", "iso": "CH"},
    {"name": "Syria", "iso": "SY"},
    {"name": "Tajikistan", "iso": "TJ"},
    {"name": "Tanzania", "iso": "TZ"},
    {"name": "Thailand", "iso": "TH"},
    {"name": "Togo", "iso": "TG"},
    {"name": "Tonga", "iso": "TO"},
    {"name": "Trinidad and Tobago", "iso": "TT"},
    {"name": "Tunisia", "iso": "TN"},
    {"name": "Turkey", "iso": "TR"},
    {"name": "Turkmenistan", "iso": "TM"},
    {"name": "Tuvalu", "iso": "TV"},
    {"name": "Uganda", "iso": "UG"},
    {"name": "Ukraine", "iso": "UA"},
    {"name": "United Arab Emirates", "iso": "AE"},
    {"name": "United Kingdom", "iso": "GB"},
    {"name": "United States", "iso": "US"},
    {"name": "Uruguay", "iso": "UY"},
    {"name": "Uzbekistan", "iso": "UZ"},
    {"name": "Vanuatu", "iso": "VU"},
    {"name": "Venezuela", "iso": "VE"},
    {"name": "Vietnam", "iso": "VN"},
    {"name": "Yemen", "iso": "YE"},
    {"name": "Zambia", "iso": "ZM"},
    {"name": "Zimbabwe", "iso": "ZW"},
]
COUNTRIES_BY_ISO = {c["iso"]: c for c in COUNTRIES}
COUNTRIES_BY_NAME = {c["name"].lower(): c["iso"] for c in COUNTRIES}


def country_by_iso(iso_code):
    """Returns {"name", "iso"} for a 2-letter ISO code, or None."""
    if not iso_code:
        return None
    return COUNTRIES_BY_ISO.get(iso_code.upper())


def country_iso_for_name(name):
    """Reverse lookup: country name -> ISO code, or None.

    Lets a live-sourced country string (e.g. OpenSky's own origin_country)
    still get a flag when its exact name happens to match this table — the
    flag is then a presentation add-on for a value whose source/confidence
    stay exactly as they were, not an enrichment result in its own right.
    Exact case-insensitive match only; no fuzzy matching, since a wrong
    match would show the wrong flag rather than just no flag.
    """
    if not name:
        return None
    return COUNTRIES_BY_NAME.get(name.strip().lower())
