"""Canonical manufacturer alias mapping.

This module holds a single authoritative mapping of observed manufacturer
strings (as reported by various upstreams) to a canonical manufacturer
name used throughout the app. The mapping was merged from two prior
inline sources and normalized into this file so it can be versioned
with the codebase and queried case-insensitively.
"""

from __future__ import annotations

from typing import Optional

# Flattened merged mapping (source -> canonical)
MANUFACTURER_ALIASES = {
  "A22 Foxbat": "Aeropro",
  "AIDC Taiwan": "AIDC",
  "ASTC Antonov": "Antonov",
  "ATR Aircraft": "ATR",
  "AVIC": "AVIC",
  "Abu Dhabi Autonomous Systems Investments": "EDGE Group",
  "Aeritalia": "Leonardo",
  "Aermacchi": "Leonardo",
  "Aero Adventure": "Aero Adventure",
  "Aero Design Ltd.": "Aero",
  "Aero Spacelines Inc.": "Aero Spacelines",
  "Aero Vodochody AEROSPACE": "Aero Vodochody",
  "Aero Vodochody a.s.": "Aero Vodochody",
  "Aero-Dynamics": "Aero-Dynamics",
  "AeroVironment Inc.": "AeroVironment",
  "AeroVironment UAV": "AeroVironment",
  "Aeromot": "Aeromot",
  "Aeronautics Defense Systems": "Aeronautics",
  "Aeronáutica Motores": "Aeromot",
  "Aeroospatiale-Embraer": "Embraer",
  "Aeropro": "Aeropro",
  "Aeropro s.r.o. (Foxbat)": "Aeropro",
  "Aerospace Industrial Development Corporation": "AIDC",
  "Aerospace Long March International": "ALIT",
  "Aerospatiale": "Airbus",
  "Aerospatiale/Alenia": "ATR",
  "Agusta": "Leonardo",
  "AgustaWestland": "Leonardo",
  "Airbus Defence and Space": "Airbus",
  "Airbus Defence and Space": "Airbus",
  "Airbus Defense, Space & Security": "Boeing",
  "Airbus Group": "Airbus",
  "Airbus Helicopters SAS": "Airbus Helicopters",
  "Airbus Industrie": "Airbus",
  "Airbus Military": "Airbus",
  "Airbus S.A.S.": "Airbus",
  "Airbus SAS": "Airbus",
  "Aircraft Industries (LET)": "Let Kunovice",
  "Alenia Aeronautica": "Leonardo",
  "Alexander Schleicher": "Schleicher",
  "Alexander Schleicher GmbH": "Schleicher",
  "American Champion Aircraft": "American Champion",
  "American Eurocopter": "Airbus Helicopters",
  "Antonov Aeronautical Scientific-Technical Complex": "Antonov",
  "Antonov Design Bureau": "Antonov",
  "Apex Aircraft": "Robin",
  "Aquila Aviation": "Aquila",
  "Aquila Aviation International": "Aquila",
  "Arado Flugzeugwerke": "Arado",
  "Armstrong Whitworth": "Hawker",
  "Atlas Aircraft Corporation": "Denel",
  "Avco Lycoming": "Lycoming",
  "Aviastar-SP": "Ilyushchev",
  "Aviat Aircraft": "Aviat",
  "Aviat Aircraft Inc": "Aviat",
  "Aviation Industry Corporation of China": "AVIC",
  "Avions Marcel Dassault": "Dassault",
  "Avions Mudry": "Apex",
  "Avions Pierre Robin": "Robin",
  "Avions de Transport Regional": "ATR",
  "Avions de Transport Régional": "ATR",
  "Avro International Aerospace": "BAE Systems",
  "Aérospatiale": "Airbus",
  "B-N Group": "Britten-Norman",
  "BAE Systems Regional Aircraft": "BAE Systems",
  "BAe": "BAE Systems",
  "BRM Aero s.r.o.": "BRM Aero",
  "Baykar Defence": "Baykar",
  "Baykar Makina": "Baykar",
  "Baykar Technologies": "Baykar",
  "Beech Aircraft Corporation": "Beechcraft",
  "Beechcraft Aircraft Company": "Beechcraft",
  "Beechcraft Corporation": "Beechcraft",
  "Bell Helicopter": "Bell",
  "Bell Helicopter Textron": "Bell",
  "Bell Textron": "Bell",
  "Bellanca Aircraft Corporation": "Bellanca",
  "Beriev Aircraft Company": "Beriev",
  "Beriev Design Bureau": "Beriev",
  "Blohm & Voss": "Blohm & Voss",
  "Boeing Commercial Airplanes": "Boeing",
  "Boeing Company": "Boeing",
  "Boeing Defense, Space & Security": "Boeing",
  "Boeing Insitu": "Insitu",
  "Boeing-McDonnell Douglas": "Boeing",
  "Bombardier Aerospace": "Bombardier",
  "Bombardier Inc.": "Bombardier",
  "Breguet Aviation": "Dassault",
  "Bristell Aircraft": "BRM Aero",
  "British Aerospace": "BAE Systems",
  "British Aerospace Hawker": "Hawker",
  "Britten-Norman Aircraft": "Britten-Norman",
  "Burkhart Grob Luft- und Raumfahrt": "Grob",
  "CAC": "Chengdu",
  "CAIC": "Changhe",
  "CASA": "Airbus",
  "COMAC": "COMAC",
  "Calidus LLC": "Calidus",
  "Canadair": "Bombardier",
  "Centre Est Aeronautique (CEA)": "Robin",
  "Cessna Aircraft": "Cessna",
  "Cessna Aircraft Co": "Cessna",
  "Cessna Aircraft Company": "Cessna",
  "Champion Aircraft": "Champion",
  "Chance Vought": "Vought",
  "Changhe Aircraft Industries Corporation": "Changhe",
  "Chengdu Aircraft Corporation": "Chengdu",
  "Chengdu Aircraft Industry Co": "Chengdu",
  "Chengdu Aircraft Industry Group": "Chengdu",
  "China Academy of Aerospace Aerodynamics": "CAAA",
  "China Aerospace Science and Technology Corporation": "CASC",
  "Christen Industries": "Aviat",
  "Cirrus Aircraft": "Cirrus",
  "Cirrus Design": "Cirrus",
  "Cirrus Design Corporation": "Cirrus",
  "Classic Aircraft Corporation": "Waco",
  "Commercial Aircraft Corp of China": "COMAC",
  "Commercial Aircraft Corporation of China": "COMAC",
  "Commercial Aircraft Corporation of China Ltd": "COMAC",
  "Commonwealth Aircraft Corporation": "CAC (Australia)",
  "Consolidated Vultee": "General Dynamics",
  "Construcciones Aeronauticas SA": "Airbus",
  "Convair": "General Dynamics",
  "Costruzioni Aeronautiche Tecnam": "Tecnam",
  "Costruzioni Aeronautiche Tecnam SpA": "Tecnam",
  "Curtiss Aeroplane and Motor": "Curtiss-Wright",
  "Curtiss-Wright Corporation": "Curtiss-Wright",
  "DASA": "Airbus",
  "DG Aviation GmbH": "DG Aviation",
  "DG Flugzeugbau": "DG Aviation",
  "DHC": "De Havilland",
  "DJI Science and Technology": "DJI",
  "Da-Jiang Innovations": "DJI",
  "Daewoo Heavy Industries Aerospace": "KAI",
  "Daher Aerospace": "Daher",
  "Daher-Socata": "Daher",
  "Dassault Aviation": "Dassault",
  "Dassault-Breguet": "Dassault",
  "Dassault-Breguet Aviation": "Dassault",
  "De Havilland Canada": "De Havilland",
  "Denel Aviation": "Denel",
  "Deutsche Aerospace": "Airbus",
  "Diamond Aircraft": "Diamond",
  "Diamond Aircraft Industries": "Diamond",
  "Dornier Flugzeugwerke": "Dornier",
  "Dornier Luftfahrt": "Dornier",
  "Dornier-Werke": "Dornier",
  "Douglas Aircraft Company": "McDonnell Douglas",
  "EADS": "Airbus",
  "ENAER Chile": "ENAER",
  "Edge Group ADASI": "EDGE Group",
  "Elbit Systems UAS": "Elbit Systems",
  "Embraer Empresa Brasileira de Aeronautica": "Embraer",
  "Embraer S.A.": "Embraer",
  "Embraer SA": "Embraer",
  "Empresa Nacional de Aeronáutica de Chile": "ENAER",
  "Eurocopter": "Airbus Helicopters",
  "Eurocopter International": "Airbus Helicopters",
  "Evektor": "Evektor",
  "Evektor-Aerotechnik": "Evektor",
  "Evolution Aircraft": "Lancair",
  "Experimental Design Bureau Myasishchev": "Myasishchev",
  "Extra Aerospace": "Extra",
  "Extra Aircraft": "Extra",
  "Extra Flugzeugbau": "Extra",
  "Extra Flugzeugproduktions": "Extra",
  "FAdeA S.A.": "FadeA",
  "FIAT Aviazione": "Aeritalia",
  "FMA": "FadeA",
  "FMA Argentina": "FadeA",
  "Fairchild Aircraft": "Fairchild",
  "Fairchild Dornier": "Dornier",
  "Fairchild Hiller": "Fairchild",
  "Fairey Aviation": "Fairey",
  "Fieseler": "Fieseler",
  "Finmeccanica": "Leonardo",
  "Flight Design General Aviation": "Flight Design",
  "Flight Design GmbH": "Flight Design",
  "Focke-Wulf": "Focke-Wulf",
  "Fokker Aerostructures": "Fokker",
  "Fokker Aircraft B.V.": "Fokker",
  "Fokker Aviation": "Fokker",
  "Fuji Heavy Industries": "Subaru",
  "Fábrica Argentina de Aviones": "FadeA",
  "Fábrica Militar de Aviones": "FadeA",
  "GA-ASI": "General Atomics",
  "GAIC": "Guizhou",
  "General Atomics Aeronautical Systems": "General Atomics",
  "General Dynamics Corporation": "General Dynamics",
  "Gloster Aircraft Company": "Hawker",
  "Government Aircraft Factories": "GAF (Australia)",
  "Great Lakes Aircraft": "Great Lakes",
  "Grob Aerospace": "Grob",
  "Grob Aircraft": "Grob",
  "Grumman Aerospace": "Northrop Grumman",
  "Grumman Aerospace Corporation": "Grumman",
  "Grumman Aircraft Engineering": "Northrop Grumman",
  "Grumman Gulfstream": "Gulfstream",
  "Guizhou Aircraft Industry Corporation": "Guizhou",
  "Gulfstream Aerospace": "Gulfstream",
  "Gulfstream Aerospace Corporation": "Gulfstream",
  "HAIG": "Harbin",
  "HAMC": "Harbin",
  "Hamburger Flugzeugbau": "Blohm & Voss",
  "Handley Page Aircraft": "Handley Page",
  "Harbin Aircraft Industry Co": "Harbin",
  "Harbin Aircraft Industry Group": "Harbin",
  "Harbin Aircraft Manufacturing Corporation": "Harbin",
  "Hawker Aircraft": "Hawker",
  "Hawker Beechcraft": "Hawker",
  "Hawker Siddeley": "Hawker",
  "Heinkel Flugzeugwerke": "Heinkel",
  "Hindustan Aeronautics Limited": "HAL",
  "Hindustan Aircraft": "HAL",
  "Hongdu Aviation Industry Group": "Hongdu",
  "Hughes Helicopters": "McDonnell Douglas",
  "IAI Malat Division": "IAI",
  "IAR Brasov": "IAR",
  "IPTN": "PTDI",
  "Icon Aircraft": "Icon",
  "Ilyushin Design Bureau": "Ilyushchev",
  "Industri Pesawat Terbang Nusantara": "PTDI",
  "Industria Aeronautica Romana": "IAR",
  "Indústria Aeronáutica Neiva": "Embraer",
  "Insitu Inc.": "Insitu",
  "Irkut Corporation": "Yakovlev",
  "Irkutsk Aviation Plant": "Yakovlev",
  "Islander Aircraft": "Britten-Norman",
  "Israel Aerospace Industries": "IAI",
  "JSC Ilyushin": "Ilyushchev",
  "JSC RSK MiG": "MiG",
  "JSC Tupolev": "Tupolev",
  "Jabiru Aircraft": "Jabiru",
  "Jakovlev": "Yakovlev",
  "Junkers Flugzeug- und Motorenwerke": "Junkers",
  "KAPO": "Tupolev",
  "KSAMC Antonov": "KSAMC",
  "Kamov Design Bureau": "Russian Helicopters",
  "Kamov Helicopters": "Russian Helicopters",
  "Kawanishi Aircraft": "ShinMaywa",
  "Kawasaki Heavy Industries": "Kawasaki",
  "Kazan Aircraft Production Association": "Tupolev",
  "Kazan Helicopters": "Russian Helicopters",
  "Kharkiv State Aircraft Manufacturing Company": "KSAMC",
  "KnAAPO": "Sukhoi",
  "Komsomolsk-on-Amur Aircraft Plant": "Sukhoi",
  "Korea Aerospace Industries": "KAI",
  "KumAPP": "Russian Helicopters",
  "Kumertau Aircraft Production Enterprise": "Russian Helicopters",
  "Kyushu Aircraft": "Kyushu",
  "LET Kunovice": "Let Kunovice",
  "LTV Aerospace": "Vought",
  "Lancair Aircraft": "Lancair",
  "Lancair International": "Lancair",
  "Lavochkin Design Bureau": "Lavochkin",
  "Learjet Corporation": "Learjet",
  "Learjet Inc.": "Learjet",
  "Ling-Temco-Vought": "Vought",
  "Lockheed Aircraft Corporation": "Lockheed Martin",
  "Lockheed Corporation": "Lockheed Martin",
  "Lockheed Martin Aeronautics": "Lockheed Martin",
  "Lockheed-Martin": "Lockheed Martin",
  "Luscombe Aircraft": "Luscombe",
  "Luscombe Airplane Corporation": "Luscombe",
  "MBB": "Airbus",
  "Macchi": "Leonardo",
  "Martin Marietta": "Lockheed Martin",
  "Maule Air": "Maule",
  "Maule Aircraft Corporation": "Maule",
  "McDonnell Aircraft": "McDonnell Douglas",
  "McDonnell Douglas Corporation": "McDonnell Douglas",
  "Messerschmitt AG": "Messerschmitt",
  "Messerschmitt-Bolkow-Blohm": "Airbus",
  "Messerschmitt-Bölkow-Blohm": "Airbus",
  "MiG Aircraft Corporation": "MiG",
  "Mikoyan Design Bureau": "MiG",
  "Mikoyan-Gurevich": "MiG",
  "Mil Helicopters": "Russian Helicopters",
  "Mil Moscow Helicopter Plant": "Russian Helicopters",
  "Mitsubishi Aircraft Corporation": "Mitsubishi",
  "Mitsubishi Heavy Industries": "Mitsubishi",
  "Mooney Airplane Company": "Mooney",
  "Mooney Aviation Company": "Mooney",
  "Moravan Aviation": "Zlin",
  "Moravan Otrokovice": "Zlin",
  "Mudry": "Apex",
  "Myasishchev Design Bureau": "Myasishchev",
  "NAMC": "Hongdu",
  "NAPO": "Sukhoi",
  "NPO Lavochkin": "Lavochkin",
  "Nakajima Aircraft Company": "Subaru",
  "Nanchang Aircraft Manufacturing Corporation": "Hongdu",
  "Neiva": "Embraer",
  "Nizhny Novgorod Aircraft Plant Sokol": "MiG",
  "Nord Aviation": "Airbus",
  "North American Aviation": "Boeing",
  "North American Rockwell": "Boeing",
  "Northrop Corporation": "Northrop Grumman",
  "Northrop Grumman Ryan": "Northrop Grumman",
  "Northrop-Grumman": "Northrop Grumman",
  "Novosibirsk Aircraft Production Association": "Sukhoi",
  "PAC Kamra": "PAC Kamra",
  "PAC NZ": "Pacific Aerospace",
  "PJSC UAC": "UAC",
  "PT Dirgantara Indonesia": "PTDI",
  "PZL Mielec": "PZL Mielec",
  "PZL Swidnik": "PZL Swidnik",
  "PZL Warszawa-Okecie": "PZL",
  "Pacific Aerospace Corporation": "Pacific Aerospace",
  "Pakistan Aeronautical Complex": "PAC Kamra",
  "Panavia Aircraft GmbH": "Panavia",
  "Patria Aviation": "Patria",
  "Pilatus Aircraft": "Pilatus",
  "Pilatus Aircraft Ltd": "Pilatus",
  "Pilatus Aircraft Ltd.": "Pilatus",
  "Piper Aircraft": "Piper",
  "Piper Aircraft Corporation": "Piper",
  "Piper Aircraft Inc": "Piper",
  "Piper Aircraft Inc.": "Piper",
  "Pipistrel Aircraft": "Pipistrel",
  "Pipistrel d.o.o.": "Pipistrel",
  "Pitts Aviation": "Aviat",
  "Polskie Zaklady Lotnicze": "PZL Mielec",
  "Progress Arsenyev Aviation Company": "Russian Helicopters",
  "Progressive Aerodyne": "Progressive Aerodyne",
  "Quicksilver Aircraft": "Quicksilver",
  "RANS Designs": "Rans",
  "Rans Aircraft": "Rans",
  "Raytheon Aircraft": "Raytheon",
  "Raytheon Aircraft Company": "Raytheon",
  "Republic Aviation Corporation": "Northrop Grumman",
  "Robin Aircraft": "Robin",
  "Robin Aviation": "Robin",
  "Rockwell International": "Boeing",
  "Rolladen-Schneider": "DG Aviation",
  "Rostvertol": "Russian Helicopters",
  "Russian Helicopters": "Russian Helicopters",
  "Ryan Aeronautical": "Northrop Grumman",
  "SAC Shenyang": "Shenyang",
  "SAMC": "Shijiazhuang",
  "SIAI-Marchetti": "Leonardo",
  "STAL Ukrainian Aircraft": "Antonov",
  "Saab AB": "Saab",
  "Saab Aircraft AB": "Saab",
  "Saab Scania": "Saab",
  "Saab-Valmet": "Saab",
  "Samsung Aerospace": "KAI",
  "Schempp-Hirth": "Schempp-Hirth",
  "Schempp-Hirth Flugzeugbau": "Schempp-Hirth",
  "Schiebel Aircraft": "Schiebel",
  "Schiebel Elektronische Geraete": "Schiebel",
  "SeaRey": "Progressive Aerodyne",
  "Semana Peru": "SEMAN",
  "Shaanxi Aircraft Corporation": "Shaanxi",
  "Shaanxi Aircraft Industry Group": "Shaanxi",
  "Shark Aero": "Shark Aero",
  "Shenyang Aircraft Corporation": "Shenyang",
  "Shenyang Aircraft Industry Group": "Shenyang",
  "Shijiazhuang Aircraft Industry Co": "Shijiazhuang",
  "Shin Maywa Industries": "ShinMaywa",
  "Short Brothers & Harland": "Shorts",
  "Sikorsky Aircraft": "Sikorsky",
  "Sikorsky Aircraft Corporation": "Sikorsky",
  "Slingsby Advanced Composites": "Slingsby",
  "Slingsby Aviation": "Slingsby",
  "Smolensk Aviation Plant": "Yak-Service",
  "Socata": "Daher",
  "Soko Mostar": "Soko",
  "Sokol Plant": "MiG",
  "Sonex Aircraft": "Sonex",
  "Sonex LLC": "Sonex",
  "Stearman Aircraft": "Boeing",
  "Stinson Aircraft Company": "Stinson",
  "Stinson Aircraft Division": "Stinson",
  "Sud Aviation": "Airbus",
  "Sukhoi Aviation Corporation": "Sukhoi",
  "Sukhoi Civil Aircraft": "Sukhoi",
  "Sukhoi Company": "Sukhoi",
  "Supermarine": "Vickers",
  "Swearingen Aircraft": "Fairchild",
  "TAI-TUSAS": "TAI",
  "TAVIA": "Beriev",
  "TL Ultralight": "TL Ultralight",
  "TUSAS Turkish Aerospace Industries": "TAI",
  "Tachikawa Aircraft": "Tachikawa",
  "Taganrog Beriev Aviation Scientific-Technical Complex": "Beriev",
  "Taylorcraft Aeroplane Company": "Taylorcraft",
  "Taylorcraft Aviation": "Taylorcraft",
  "Tecnam": "Tecnam",
  "Tecnam Aircraft": "Tecnam",
  "Textron Aviation Beechcraft": "Beechcraft",
  "Textron Aviation Cessna": "Cessna",
  "Textron eAviation Pipistrel": "Pipistrel",
  "The Boeing Company": "Boeing",
  "Tupolev Design Bureau": "Tupolev",
  "Turkish Aerospace Industries (TAI)": "TAI",
  "UAC": "UAC",
  "UUAP": "Russian Helicopters",
  "Ulan-Ude Aviation Plant": "Russian Helicopters",
  "United Aircraft Corporation": "UAC",
  "VASO": "Ilyushchev",
  "VFW-Fokker": "Airbus",
  "Valmet Aviation": "Patria",
  "Valmet Oy": "Patria",
  "Van's Aircraft Inc": "Van's Aircraft",
  "Vans Aircraft": "Van's Aircraft",
  "Viking Air": "De Havilland",
  "Viking Air Limited": "De Havilland",
  "Voronezh Aircraft Production Association": "Ilyushchev",
  "Vought Aircraft": "Vought",
  "WACO Aircraft Corporation": "Waco",
  "Westland Helicopters": "Leonardo",
  "Wright Aeronautical": "Curtiss-Wright",
  "XAC": "Xi'an",
  "Xi'an Aircraft Industrial Corporation": "Xi'an",
  "Xi'an Aircraft Industry Co": "Xi'an",
  "Xi'an Aircraft Manufacturing Corporation": "Xi'an",
  "Xian Aircraft": "Xi'an",
  "Yakovlev Aircraft": "Yakovlev",
  "Yakovlev Design Bureau": "Yakovlev",
  "Zenair": "Zenith",
  "Zenith Aircraft Company": "Zenith",
  "Zlin Aircraft": "Zlin",
  "Zlin Aviation s.r.o.": "Zlin",
  "de Havilland Canada": "De Havilland"
}


# Build a lowercased lookup for case-insensitive matching
_LOWER_MAP = {k.lower(): v for k, v in MANUFACTURER_ALIASES.items()}


def normalize_manufacturer(name: str) -> Optional[str]:
    """Return a canonical manufacturer name for a possibly-variant input.

    Returns the canonical string when a mapping exists, or the original
    input stripped when no mapping matched. Input of `None` returns
    `None`.
    """
    if not name:
        return None
    key = name.strip().lower()
    return _LOWER_MAP.get(key) or name.strip()
